// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// runifC
NumericVector runifC(int n);
RcppExport SEXP _StatComp20015_runifC(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(runifC(n));
    return rcpp_result_gen;
END_RCPP
}
// rnormC
double rnormC(double E, double se);
RcppExport SEXP _StatComp20015_rnormC(SEXP ESEXP, SEXP seSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type E(ESEXP);
    Rcpp::traits::input_parameter< double >::type se(seSEXP);
    rcpp_result_gen = Rcpp::wrap(rnormC(E, se));
    return rcpp_result_gen;
END_RCPP
}
// rw_MetropolisC
List rw_MetropolisC(double sigma, double x0, int N);
RcppExport SEXP _StatComp20015_rw_MetropolisC(SEXP sigmaSEXP, SEXP x0SEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(rw_MetropolisC(sigma, x0, N));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_StatComp20015_runifC", (DL_FUNC) &_StatComp20015_runifC, 1},
    {"_StatComp20015_rnormC", (DL_FUNC) &_StatComp20015_rnormC, 2},
    {"_StatComp20015_rw_MetropolisC", (DL_FUNC) &_StatComp20015_rw_MetropolisC, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_StatComp20015(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
