# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Random sampler between 0 and 1 using Rcpp
#' @description Generate n random numbers between 0 and 1 using Rcpp
#' @param n the number of samples
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' rnC <- runifC(100)
#' plot(rnC,type='l')
#' }
#' @export
runifC <- function(n) {
    .Call('_StatComp20015_runifC', PACKAGE = 'StatComp20015', n)
}

#' @title A normally distributed sampler using Rcpp
#' @description Generate a normally distributed random sample using Rcpp
#' @param E the mean of a normal distribution
#' @param se the standard error of a normal distribution
#' @return a random sample of size 1
#' @examples
#' \dontrun{
#' rnC <- replicate(100,rnormC(5,1))
#' plot(rnC,type='l')
#' }
#' @export
rnormC <- function(E, se) {
    .Call('_StatComp20015_rnormC', PACKAGE = 'StatComp20015', E, se)
}

#' @title A random walk Metropolis sampler using Rcpp
#' @description A random walk Metropolis sampler for generating the standard Laplace distribution using Rcpp
#' @param sigma given standard deviation
#' @param x0 the initial value given
#' @param N the length of the resulting chain
#' @return a list of a chain of size \code{n} and the number of times it is accepted during the process of using this method
#' @examples
#' \dontrun{
#' N <- 2000
#' rwk <- rw_MetropolisC(2,20,N)
#' plot(rwk$x,type='l')
#' accept.rate <- rwk$k/N
#' }
#' @export
rw_MetropolisC <- function(sigma, x0, N) {
    .Call('_StatComp20015_rw_MetropolisC', PACKAGE = 'StatComp20015', sigma, x0, N)
}

